// SPDX-License-Identifier: MIT

#ifndef DATACRUMBS_UTILS_COMMON_CONSTANTS_H
#define DATACRUMBS_UTILS_COMMON_CONSTANTS_H

#define DATACRUMBS_ENV_LOG_DIR "DATACRUMBS_LOG_DIR"
#define DATACRUMBS_ENV_USER "DATACRUMBS_USER"
#define DATACRUMBS_ENV_INSTALL_DATA_DIR "DATACRUMBS_INSTALL_DATA_DIR"
#define DATACRUMBS_ENV_CONFIGURED_TRACE_DIR "DATACRUMBS_CONFIGURED_TRACE_DIR"
#define DATACRUMBS_ENV_SINK_INDEX "DATACRUMBS_SINK_INDEX"
#define DATACRUMBS_ENV_PFW_ASYNC "DATACRUMBS_PFW_ASYNC"
#define DATACRUMBS_ENV_PFW_LEVEL "DATACRUMBS_PFW_LEVEL"
#define DATACRUMBS_ENV_RING_MB "DATACRUMBS_RING_MB"
#define DATACRUMBS_ENV_DPA_REARM "DATACRUMBS_DPA_REARM"
#define DATACRUMBS_ENV_COMPRESS_THREADS "DATACRUMBS_COMPRESS_THREADS"
#define DATACRUMBS_ENV_WORKER_CPUS "DATACRUMBS_WORKER_CPUS"

#define DATACRUMBS_ENV_POSIX "DATACRUMBS_POSIX"
// Aggregation is one global feature, as in dftracer: whether records fold into interval buckets,
// and whether that covers everything or only a module's named selection. The per-module enables
// above say which modules run; this says what they do with what they capture. Selections stay in
// the probe yaml, not a separate aggregation file.

// Path to the settings the configurator resolved from the probe yaml.
#define DATACRUMBS_ENV_CLIENT_CONFIG "DATACRUMBS_CLIENT_CONFIG"

#define DATACRUMBS_ENV_ENABLE_AGGREGATION "DATACRUMBS_ENABLE_AGGREGATION"
#define DATACRUMBS_ENV_AGGREGATION_TYPE "DATACRUMBS_AGGREGATION_TYPE"

#define DATACRUMBS_ENV_POSIX_RECORD "DATACRUMBS_POSIX_RECORD"
#define DATACRUMBS_ENV_POSIX_AGGREGATE "DATACRUMBS_POSIX_AGGREGATE"
#define DATACRUMBS_ENV_POSIX_OFF "DATACRUMBS_POSIX_OFF"
#define DATACRUMBS_ENV_POSIX_DEBUG "DATACRUMBS_POSIX_DEBUG"

#define DATACRUMBS_ENV_STDIO "DATACRUMBS_STDIO"
#define DATACRUMBS_ENV_STDIO_RECORD "DATACRUMBS_STDIO_RECORD"
#define DATACRUMBS_ENV_STDIO_AGGREGATE "DATACRUMBS_STDIO_AGGREGATE"
#define DATACRUMBS_ENV_STDIO_OFF "DATACRUMBS_STDIO_OFF"
#define DATACRUMBS_ENV_STDIO_OUT "DATACRUMBS_STDIO_OUT"

#define DATACRUMBS_ENV_API "DATACRUMBS_API"
#define DATACRUMBS_ENV_API_RECORD "DATACRUMBS_API_RECORD"
#define DATACRUMBS_ENV_API_AGGREGATE "DATACRUMBS_API_AGGREGATE"
#define DATACRUMBS_ENV_API_OFF "DATACRUMBS_API_OFF"
#define DATACRUMBS_ENV_API_OUT "DATACRUMBS_API_OUT"
#define DATACRUMBS_ENV_API_CONFIG "DATACRUMBS_API_CONFIG"
#define DATACRUMBS_ENV_API_DEBUG "DATACRUMBS_API_DEBUG"

#define DATACRUMBS_ENV_ENGINE "DATACRUMBS_ENGINE"
// Named for the DOCA fixed-function engines and the DOCA RDMA path this module reads, so it is not
// mistaken for the DPA, which is programmable, has its own DATACRUMBS_DPA* namespace and its own
// telemetry plugin, and never runs these operations.
#define DATACRUMBS_ENV_ENGINE_RECORD "DATACRUMBS_DOCA_ENGINE_RECORD"
#define DATACRUMBS_ENV_ENGINE_AGGREGATE "DATACRUMBS_DOCA_ENGINE_AGGREGATE"
#define DATACRUMBS_ENV_ENGINE_OFF "DATACRUMBS_DOCA_ENGINE_OFF"
#define DATACRUMBS_ENV_ENGINE_WRAPS "DATACRUMBS_ENGINE_WRAPS"
#define DATACRUMBS_ENV_ENGINE_OUT "DATACRUMBS_ENGINE_OUT"
#define DATACRUMBS_ENV_ENGINE_STATS "DATACRUMBS_ENGINE_STATS"
#define DATACRUMBS_ENV_ENGINE_JOIN "DATACRUMBS_ENGINE_JOIN"
#define DATACRUMBS_ENV_ENGINE_SCAN_CACHE "DATACRUMBS_ENGINE_SCAN_CACHE"
// Timer drain: how often a dedicated thread sweeps every bound CQ, independent of the app's own
// doca_pe_progress calls. Microseconds, since 100us is well under the millisecond scale the shared
// telemetry interval uses elsewhere.
#define DATACRUMBS_ENV_ENGINE_DRAIN_US "DATACRUMBS_ENGINE_DRAIN_US"
// records (default) keeps one JSON line per completion; aggregate rolls it into per-CQ
// per-window counters, using the shared ENABLE_AGGREGATION / AGGREGATION_TYPE pair. That pair
// buckets duration generically, rather than each CQ keeping its own histogram.
#define DATACRUMBS_ENV_ENGINE_CAPTURE_MODE "DATACRUMBS_ENGINE_CAPTURE_MODE"
// In aggregate capture mode, additionally emit every Nth completion as a full per-record event.
// 0 (default) means none.
#define DATACRUMBS_ENV_ENGINE_SAMPLE "DATACRUMBS_ENGINE_SAMPLE"

#define DATACRUMBS_ENV_HWTS "DATACRUMBS_HWTS"
#define DATACRUMBS_ENV_HWTS_RECORD "DATACRUMBS_HWTS_RECORD"
#define DATACRUMBS_ENV_HWTS_AGGREGATE "DATACRUMBS_HWTS_AGGREGATE"
#define DATACRUMBS_ENV_HWTS_OFF "DATACRUMBS_HWTS_OFF"
#define DATACRUMBS_ENV_HWTS_OUT "DATACRUMBS_HWTS_OUT"
#define DATACRUMBS_ENV_HWTS_DOCA "DATACRUMBS_HWTS_DOCA"
#define DATACRUMBS_ENV_HWTS_DOCA_DEV "DATACRUMBS_HWTS_DOCA_DEV"
#define DATACRUMBS_ENV_HWTS_POST_OP "DATACRUMBS_HWTS_POST_OP"
#define DATACRUMBS_ENV_HW_COUNTERS "DATACRUMBS_HW_COUNTERS"
#define DATACRUMBS_ENV_HWTS_SAMPLE "DATACRUMBS_HWTS_SAMPLE"
#define DATACRUMBS_ENV_HWTS_UPROBE "DATACRUMBS_HWTS_UPROBE"
#define DATACRUMBS_ENV_HWTS_POSTHOOK "DATACRUMBS_HWTS_POSTHOOK"
#define DATACRUMBS_ENV_HWTS_DOORBELL "DATACRUMBS_HWTS_DOORBELL"

#define DATACRUMBS_ENV_PROGRAM "DATACRUMBS_PROGRAM"
#define DATACRUMBS_ENV_PROGRAM_OUT "DATACRUMBS_PROGRAM_OUT"
#define DATACRUMBS_ENV_PROGRAM_SINK "DATACRUMBS_PROGRAM_SINK"

#define DATACRUMBS_ENV_WINDOW_OUT "DATACRUMBS_WINDOW_OUT"

#define DATACRUMBS_ENV_CLOCK "DATACRUMBS_CLOCK"

#define DATACRUMBS_ENV_TIMESYNC_SNAPSHOT "DATACRUMBS_TIMESYNC_SNAPSHOT"
#define DATACRUMBS_ENV_TIMESYNC_RAW_DEV "DATACRUMBS_TIMESYNC_RAW_DEV"
#define DATACRUMBS_ENV_TIMESYNC_CLOCK_INFO_REFRESH_MS "DATACRUMBS_TIMESYNC_CLOCK_INFO_REFRESH_MS"
#define DATACRUMBS_ENV_TIMESYNC_CLOCK_INFO_INTERVAL_MS "DATACRUMBS_TIMESYNC_CLOCK_INFO_INTERVAL_MS"

#define DATACRUMBS_ENV_SERVER_RUN_ID "DATACRUMBS_SERVER_RUN_ID"

#define DATACRUMBS_ENV_DPA "DATACRUMBS_DPA"
#define DATACRUMBS_ENV_DPA_OUT "DATACRUMBS_DPA_OUT"
#define DATACRUMBS_ENV_DPA_ANCHOR "DATACRUMBS_DPA_ANCHOR"
#define DATACRUMBS_ENV_DPA_EVENT_SAMPLES "DATACRUMBS_DPA_EVENT_SAMPLES"
#define DATACRUMBS_ENV_DPA_MODE "DATACRUMBS_DPA_MODE"
#define DATACRUMBS_ENV_DPA_KEEP_ANCHOR "DATACRUMBS_DPA_KEEP_ANCHOR"
#define DATACRUMBS_ENV_DPA_ANCHOR_INTERVAL_S "DATACRUMBS_DPA_ANCHOR_INTERVAL_S"
// "rpc" (default) or "window"; see datacrumbs::client::dpa::AnchorMode.
#define DATACRUMBS_ENV_DPA_ANCHOR_MODE "DATACRUMBS_DPA_ANCHOR_MODE"
// Window mode only: how long the burst kernel runs, on the DPA's own clock.
#define DATACRUMBS_ENV_DPA_ANCHOR_BURST_US "DATACRUMBS_DPA_ANCHOR_BURST_US"
// Substring matched against a device's PCI address, same convention as
// DATACRUMBS_ENV_HWTS_DOCA_DEV. Empty means the first device that offers a DPA context.
#define DATACRUMBS_ENV_DPA_DEV "DATACRUMBS_DPA_DEV"
// The anchor's dpacc --app-name, which the device also reports back as the DPA process's own
// name. The build and the dpa_telemetry plugin share this constant, so the plugin does not sample
// the anchor process as if it were the traced workload.
#define DATACRUMBS_DPA_ANCHOR_PROCESS_NAME "dc_dpa_anchor"
#define DATACRUMBS_ENV_DOCA_DIAG_GROUPS "DATACRUMBS_DOCA_DIAG_GROUPS"

#endif  // DATACRUMBS_UTILS_COMMON_CONSTANTS_H
