"""Emit the ops table: every classified symbol, how it is traced, and what its record says.

Written from the same inputs the shim is built from - the inventory and the generated lists - so
this reference cannot drift from what the code does.

Markdown by default; --format tsv for the analysis pipeline.
"""

import argparse
import re
from collections import Counter, defaultdict
from pathlib import Path

WRAP_RE = re.compile(r"^\s*X\(([A-Za-z0-9_]+), *([a-z]+),")
TRAMP_RE = re.compile(r"^\s*T\(([A-Za-z0-9_]+), *([a-z]+)\)")
VERSION_RE = re.compile(r'^#define DC_BUILT_AGAINST_([A-Z0-9]+) +"([^"]+)"')

# What each class means in a record's `cat`: the vocabulary a reader groups on, so it describes the
# operation rather than our implementation.
CLASS_MEANING = {
    "submit": "work handed to the device",
    "poll": "waiting, draining or arming for completion",
    "construct": "building a descriptor or task before submission",
    "connect": "pairing two endpoints",
    "command": "a direct firmware command carrying its own opcode",
    "memory": "region registration, teardown and direct copies",
    "lifecycle": "makes or unmakes an object",
    "query": "reads state; nothing happens on the device",
    "capability": "asks what the device supports",
    "other": "unclassified",
}


def read_wrap(path):
    covered, versions = {}, {}
    if not path or not Path(path).exists():
        return covered, versions
    for line in Path(path).read_text().splitlines():
        m = WRAP_RE.match(line)
        if m:
            covered[m.group(1)] = m.group(2)
            continue
        v = VERSION_RE.match(line)
        if v:
            versions[v.group(1).lower()] = v.group(2)
    return covered, versions


def read_tramp(path):
    if not path or not Path(path).exists():
        return {}
    out = {}
    for line in Path(path).read_text().splitlines():
        m = TRAMP_RE.match(line)
        if m:
            out[m.group(1)] = m.group(2)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--inventory", default=str(Path(__file__).parent / "api-inventory.tsv"))
    ap.add_argument("--wrap-list")
    ap.add_argument("--tramp-list")
    ap.add_argument("--format", choices=("md", "tsv"), default="md")
    ap.add_argument("--output")
    args = ap.parse_args()

    wrapped, versions = read_wrap(args.wrap_list)
    tramped = read_tramp(args.tramp_list)

    rows = []
    for line in Path(args.inventory).read_text().splitlines()[1:]:
        if not line.strip():
            continue
        lib, sym, cls = line.split("\t")
        if sym in wrapped:
            how = "gotcha"
        elif sym in tramped:
            how = "trampoline"
        else:
            how = "none"
        rows.append((lib, sym, cls, how))

    out = open(args.output, "w") if args.output else None

    def p(s=""):
        print(s, file=out) if out else print(s)

    if args.format == "tsv":
        p("library\tsymbol\tclass\tmechanism")
        for r in sorted(rows):
            p("\t".join(r))
        if out:
            out.close()
        return

    by_class = Counter(c for _, _, c, _ in rows)
    by_how = Counter(h for _, _, _, h in rows)
    by_lib = defaultdict(Counter)
    for lib, _, cls, _ in rows:
        by_lib[lib][cls] += 1

    p("# Ops table")
    p()
    p("Generated by `gen_ops_table.py`. Every classified symbol in the ibverbs, mlx5 and DOCA")
    p("stacks, what its record's `cat` will say, and how it is intercepted.")
    p()
    if versions:
        p("Built against: " + ", ".join(f"{k} {v}" for k, v in sorted(versions.items())) + ".")
        p("A trace decodes opcodes and flags with names from these headers, so it is only")
        p("interpretable against a matching library; the sink records each library's build id.")
        p()

    p("## What a class means")
    p()
    p("`cat` in every record. This is the vocabulary a reader groups on.")
    p()
    p("| class | meaning | symbols |")
    p("|---|---|---|")
    for cls, n in by_class.most_common():
        p(f"| `{cls}` | {CLASS_MEANING.get(cls, '')} | {n} |")
    p()

    p("## How each is intercepted")
    p()
    p("| mechanism | symbols | why |")
    p("|---|---|---|")
    p(f"| GOTCHA | {by_how['gotcha']} | a header declares it, so a wrapper can forward its "
      "arguments |")
    p(f"| trampoline | {by_how['trampoline']} | exported but undeclared, or variadic; entry only, "
      "since no prototype exists |")
    p(f"| none | {by_how['none']} | unclassified, so deliberately not traced |")
    p()
    p("The ibverbs hot path is absent from both: `ibv_post_send` and `ibv_poll_cq` are")
    p("`static inline` over `qp->context->ops`, so no symbol exists to bind. Those are patched in")
    p("the dispatch table by `rdma_hwts.cpp`.")
    p()

    p("## By library")
    p()
    p("| library | symbols | submit | poll | memory | lifecycle |")
    p("|---|---|---|---|---|---|")
    for lib in sorted(by_lib, key=lambda x: -sum(by_lib[x].values())):
        c = by_lib[lib]
        p(f"| {lib} | {sum(c.values())} | {c['submit']} | {c['poll']} | {c['memory']} "
          f"| {c['lifecycle']} |")
    p()

    p("## Every symbol")
    p()
    p("| symbol | library | cat | mechanism |")
    p("|---|---|---|---|")
    for lib, sym, cls, how in sorted(rows, key=lambda r: (r[2], r[1])):
        p(f"| `{sym}` | {lib} | `{cls}` | {how} |")

    if out:
        out.close()


if __name__ == "__main__":
    main()
