"""Generate the trampoline list: classified symbols that no header declares.

GOTCHA needs a prototype to forward arguments, so gen_gotcha.py covers only what libclang reads
from a header. That leaves the ibv_cmd_* kernel-command layer (its header ships with rdma-core's
provider package, not the runtime), the IBVERBS_PRIVATE and DOCA INTERNAL version nodes, and the
variadic functions, which no C wrapper can forward under AAPCS64.

A trampoline needs no prototype: it saves the argument registers, records the entry, restores them
and tail-jumps, so the callee sees exactly what the caller passed.
"""

import argparse
import re
import sys
from pathlib import Path

# `other` is the absence of a classification, not a class.
SKIP_CLASSES = ("other",)

WRAPPED_RE = re.compile(r"^\s*X\(([A-Za-z0-9_]+),")
TRAMP_RE = re.compile(r"^\s*T\(([A-Za-z0-9_]+),")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--inventory", default=str(Path(__file__).parent / "api-inventory.tsv"))
    ap.add_argument("--wrap-list", help="api_wrap_list.h; its symbols are already covered")
    ap.add_argument(
        "--also-covered",
        action="append",
        default=[],
        help="another DC_TRAMP_FUNCS list whose symbols are already defined; two lists that both "
        "name a symbol would define it twice and fail the link",
    )
    ap.add_argument("--libs", default="", help="comma-separated inventory libraries; default all")
    ap.add_argument("--output", help="write here instead of stdout")
    ap.add_argument("--skip-classes", default=",".join(SKIP_CLASSES))
    args = ap.parse_args()

    covered = set()
    if args.wrap_list and Path(args.wrap_list).exists():
        for line in Path(args.wrap_list).read_text().splitlines():
            m = WRAPPED_RE.match(line)
            if m:
                covered.add(m.group(1))
    for other in args.also_covered:
        if Path(other).exists():
            for line in Path(other).read_text().splitlines():
                m = TRAMP_RE.match(line)
                if m:
                    covered.add(m.group(1))

    want_lib = set(filter(None, args.libs.split(",")))
    skip = set(filter(None, args.skip_classes.split(",")))

    rows = []
    for line in Path(args.inventory).read_text().splitlines()[1:]:
        if not line.strip():
            continue
        lib, sym, cls = line.split("\t")
        if cls in skip or sym in covered:
            continue
        if want_lib and lib not in want_lib:
            continue
        rows.append((sym, cls))

    out = open(args.output, "w") if args.output else sys.stdout
    print("// Generated by gen_tramp.py. Do not edit by hand.", file=out)
    print("// T(name, class)", file=out)
    print("#define DC_TRAMP_FUNCS(T) \\", file=out)
    for sym, cls in sorted(rows):
        print(f"  T({sym}, {cls}) \\", file=out)
    print(file=out)
    print(f"// {len(rows)} trampolined, {len(covered)} already wrapped", file=out)


if __name__ == "__main__":
    main()
