capture_probes:
  - name: custom1
    start_event_id: 100000
    probe: custom
    type: custom
    file: @DATACRUMBS_CUSTOM_PROBE_BPF@
    probes: @DATACRUMBS_CUSTOM_PROBE_DEFINITION@
    process_header: @DATACRUMBS_CUSTOM_PROBE_PROCESS_HEADER@
    event_type: 2
  - name: libc
    probe: uprobe
    type: binary
    file: @DATACRUMBS_LIBC_SO@
    regex: .*fork.*
  - name: python
    probe: usdt
    type: usdt
    binary_path: @DATACRUMBS_PYTHON_LIB@
    provider: python
  - name: os_page_cache
    probe: kprobe
    type: header
    file: @DATACRUMBS_KERNEL_HEADERS_PATH@/include/linux/pagemap.h
  - name: shm
    probe: kprobe
    type: header
    file: @DATACRUMBS_KERNEL_HEADERS_PATH@/include/linux/shmem_fs.h
  - name: iomap
    probe: kprobe
    type: ksym
    regex: ^iomap(?!.*cold).*
