// SPDX-License-Identifier: MIT

#ifndef DATACRUMBS_UTILS_CLIENT_GOTCHA_WRAP_H
#define DATACRUMBS_UTILS_CLIENT_GOTCHA_WRAP_H

#include <datacrumbs/utils/common/clock.h>
#include <datacrumbs/utils/common/pfw_sink.h>
#include <gotcha/gotcha.h>
#include <sys/syscall.h>
#include <time.h>
#include <unistd.h>

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <type_traits>

/**
 * @brief Wraps the classified API surface with GOTCHA, one wrapper per symbol.
 *
 * Expand DC_WRAPPED_FUNCS (generated by scripts/datacrumbs/gen_gotcha.py) with DC_GOTCHA_DECL,
 * DC_GOTCHA_WRAPPER and DC_GOTCHA_BINDING, in that order. Define DC_GOTCHA_SINK and
 * DC_GOTCHA_STACK first.
 *
 * The ibverbs hot path is not reachable here: ibv_post_send and ibv_poll_cq are static inline over
 * qp->context->ops, so no symbol exists to bind. Those are patched in the dispatch table by
 * rdma_hwts.cpp. See reverse-eng/findings/api-coverage.md.
 */

namespace datacrumbs::client::gotcha_wrap {

using datacrumbs::client::mono_ns;

inline thread_local int g_in_wrapper = 0;

/// Suppresses recording while inside a wrapper: the sink formats and writes, which can re-enter.
struct Guard {
  bool entered;
  Guard() : entered(g_in_wrapper == 0) {
    if (entered) g_in_wrapper = 1;
  }
  ~Guard() {
    if (entered) g_in_wrapper = 0;
  }
};

/// Whether @p name aggregates rather than records, under this module's mode and its exception
/// lists. Called from a function-local static in each generated wrapper, so the pattern match runs
/// once per symbol rather than once per call.
inline bool aggregates(const char* name) {
  const auto& rt = ConfigurationManager::runtime();
  return ConfigurationManager::mode_for(rt.api_mode, rt.api_select, name) ==
         ConfigurationManager::CaptureMode::AGGREGATE;
}

/// @p args is a pre-formatted fragment, each element leading with a comma. @p nums/@p nnums is
/// the same call's numeric args again, unformatted, for the aggregate path: RECORD mode uses
/// args and ignores nums, AGGREGATE mode uses nums and never formats args at all.
inline void emit(PfwSink* sink, const char* name, const char* cls, const char* stack,
                 bool aggregate, std::uint64_t start_ns, std::uint64_t dur_ns, const char* args,
                 const NumArg* nums, int nnums) {
  if (sink == nullptr) return;
  if (aggregate) {
    sink->aggregate(name, cls, stack, start_ns, dur_ns, nums, nnums);
    return;
  }
  // Nanoseconds in, microseconds out: the reader's dur is microseconds, and dividing here rather
  // than at the call site keeps the full resolution for the aggregate above.
  const std::uint64_t dur_us = dur_ns / DATACRUMBS_TIME_DIVISOR_NS;
  char line[1024];
  const int n = std::snprintf(
      line, sizeof(line),
      R"({"id":%llu,"name":"%s","cat":"%s","type":"%s","pid":%ld,"tid":%d,"ts":%llu,"dur":%llu,"ph":1,"args":{"hhash":"%s"%s,"tool":"gotcha"}})"
      "\n",
      static_cast<unsigned long long>(sink->next_id()), name, cls, stack,
      static_cast<long>(datacrumbs::client::self_pid()), static_cast<int>(datacrumbs::client::self_tid()),
      static_cast<unsigned long long>(sink->clock().remap(start_ns) / DATACRUMBS_TIME_DIVISOR_NS),
      static_cast<unsigned long long>(dur_us), sink->hhash().c_str(), args);
  if (n > 0) sink->write(line, static_cast<std::size_t>(n));
}

/// Records a wrapped call's return as a "ret" arg, but only where the return is a quantity: a
/// byte count (ssize_t, size_t), not a status (int: 0/errno/DOCA error) or an identity (pointer,
/// enum). Templated so the untaken branches below are never compiled for a mismatched Ret -
/// otherwise a pointer return would fail to compile against the integer casts here. A negative
/// ssize_t means the call moved nothing; it is recorded as 0 rather than as a corrupt huge
/// unsigned value or a negative sum polluting the aggregate.
template <typename Ret>
inline void capture_ret([[maybe_unused]] Ret r, [[maybe_unused]] char* args,
                        [[maybe_unused]] int& n, [[maybe_unused]] std::size_t cap,
                        [[maybe_unused]] NumArg* nums, [[maybe_unused]] int& nn) {
  if constexpr (std::is_same_v<Ret, ssize_t>) {
    const long long v = r > 0 ? static_cast<long long>(r) : 0;
    n += std::snprintf(args + n, cap - n, ",\"ret\":%lld", v);
    if (nn < kMaxAggArgs) {
      nums[nn].key = "ret";
      nums[nn].kind = NumKind::INT;
      nums[nn].i = v;
      ++nn;
    }
  } else if constexpr (std::is_same_v<Ret, size_t>) {
    const unsigned long long v = static_cast<unsigned long long>(r);
    n += std::snprintf(args + n, cap - n, ",\"ret\":%llu", v);
    if (nn < kMaxAggArgs) {
      nums[nn].key = "ret";
      nums[nn].kind = NumKind::UINT;
      nums[nn].u = v;
      ++nn;
    }
  }
}

}  // namespace datacrumbs::client::gotcha_wrap

// A pointer is recorded as an identity, not dereferenced: the same qp on a post and its completion
// is what joins them, but reading through it needs the provider's layout.
#define DC_A_INT(x)                                                                      \
  _dc_n += std::snprintf(_dc_args + _dc_n, sizeof(_dc_args) - _dc_n, ",\"" #x "\":%lld", \
                         static_cast<long long>(x));                                     \
  if (_dc_nn < datacrumbs::client::kMaxAggArgs) {                                        \
    _dc_nums[_dc_nn].key = #x;                                                           \
    _dc_nums[_dc_nn].kind = datacrumbs::client::NumKind::INT;                            \
    _dc_nums[_dc_nn].i = static_cast<long long>(x);                                      \
    ++_dc_nn;                                                                            \
  }
#define DC_A_PTR(x)                                                                        \
  _dc_n += std::snprintf(_dc_args + _dc_n, sizeof(_dc_args) - _dc_n, ",\"" #x "\":\"%p\"", \
                         reinterpret_cast<const void*>(x));

// An ordinal means nothing to a reader, so an enum records its constant name. A value the header
// does not name falls back to the number rather than being dropped: an unnamed value in a trace is
// usually the interesting one.
// A flag word decodes to the constants it sets, joined by |, with the raw value kept alongside so a
// bit the header does not name is still visible.
#define DC_A_FLAGS(x, decoder)                                                                 \
  {                                                                                            \
    char _dc_f[256];                                                                           \
    const int _dc_fn = dc_flags_##decoder(static_cast<long long>(x), _dc_f, sizeof(_dc_f));    \
    _dc_n += std::snprintf(_dc_args + _dc_n, sizeof(_dc_args) - _dc_n, ",\"" #x "\":\"%s\"",   \
                           _dc_fn > 0 ? _dc_f : "0");                                          \
    _dc_n += std::snprintf(_dc_args + _dc_n, sizeof(_dc_args) - _dc_n, ",\"" #x "_raw\":%lld", \
                           static_cast<long long>(x));                                         \
  }

// The opcode inside a command buffer: mlx5 puts it in the first two bytes, big endian. Bounds
// checked, since a caller may pass a short buffer and the wrapper must not read past it.
#define DC_A_CMD(buf, len, decoder)                                                             \
  if ((buf) != nullptr && (len) >= 2) {                                                         \
    const auto* _dc_b = reinterpret_cast<const unsigned char*>(buf);                            \
    const long long _dc_op = (static_cast<long long>(_dc_b[0]) << 8) | _dc_b[1];                \
    const char* _dc_c = dc_enum_##decoder(_dc_op);                                              \
    if (_dc_c != nullptr)                                                                       \
      _dc_n +=                                                                                  \
          std::snprintf(_dc_args + _dc_n, sizeof(_dc_args) - _dc_n, ",\"cmd\":\"%s\"", _dc_c);  \
    else                                                                                        \
      _dc_n += std::snprintf(_dc_args + _dc_n, sizeof(_dc_args) - _dc_n, ",\"cmd\":\"0x%llx\"", \
                             _dc_op);                                                           \
  }

// An op carried in an attribute struct: read the field at a machine-computed offset and name it.
// The pointer is checked, since a caller may legitimately pass null for an optional attribute, and
// the width comes from the header so a uint8_t field is not read as a word.
#define DC_A_FIELD(ptr, off, width, label, decoder)                                                \
  if ((ptr) != nullptr) {                                                                          \
    const auto* _dc_p = reinterpret_cast<const unsigned char*>(ptr) + (off);                       \
    unsigned long long _dc_v = 0;                                                                  \
    __builtin_memcpy(&_dc_v, _dc_p, (width));                                                      \
    const char* _dc_fn = dc_enum_##decoder(static_cast<long long>(_dc_v));                         \
    if (_dc_fn != nullptr)                                                                         \
      _dc_n += std::snprintf(_dc_args + _dc_n, sizeof(_dc_args) - _dc_n, ",\"" #label "\":\"%s\"", \
                             _dc_fn);                                                              \
    else                                                                                           \
      _dc_n += std::snprintf(_dc_args + _dc_n, sizeof(_dc_args) - _dc_n, ",\"" #label "\":%llu",   \
                             _dc_v);                                                               \
  }

#define DC_A_ENUM(x, decoder)                                                                     \
  {                                                                                               \
    const char* _dc_e = dc_enum_##decoder(static_cast<long long>(x));                             \
    if (_dc_e != nullptr)                                                                         \
      _dc_n +=                                                                                    \
          std::snprintf(_dc_args + _dc_n, sizeof(_dc_args) - _dc_n, ",\"" #x "\":\"%s\"", _dc_e); \
    else                                                                                          \
      _dc_n += std::snprintf(_dc_args + _dc_n, sizeof(_dc_args) - _dc_n, ",\"" #x "\":%lld",      \
                             static_cast<long long>(x));                                          \
  }

#define DC_GOTCHA_DECL(name, cls, ret, params, vargs, argrecs, is_void) \
  typedef ret(*name##_fptr) params;                                     \
  static gotcha_wrappee_handle_t name##_handle;

#define DC_GOTCHA_RECORD(name, cls, argrecs, retcap)                                             \
  char _dc_args[512];                                                                            \
  [[maybe_unused]] int _dc_n = 0;                                                                \
  _dc_args[0] = '\0';                                                                            \
  /* Sized for aggregate mode only; RECORD mode's _dc_args string above is unaffected. */        \
  datacrumbs::client::NumArg _dc_nums[datacrumbs::client::kMaxAggArgs];                          \
  [[maybe_unused]] int _dc_nn = 0;                                                               \
  /* Once per symbol, not once per call: a match per call would cost more than aggregating saves \
   */                                                                                            \
  static const bool _dc_agg = datacrumbs::client::gotcha_wrap::aggregates(#name);                \
  argrecs retcap datacrumbs::client::gotcha_wrap::emit(                                          \
      DC_GOTCHA_SINK, #name, #cls, DC_GOTCHA_STACK, _dc_agg, _dc_t0, _dc_t1 - _dc_t0, _dc_args,  \
      _dc_nums, _dc_nn);

// _dc_r is declared before the null check so the early return has a value; `ret()` cannot be
// written for a pointer return without parsing as a function type.
#define DC_GOTCHA_WRAPPER_0(name, cls, ret, params, vargs, argrecs)                    \
  static ret name##_dcwrap params {                                                    \
    ret _dc_r{};                                                                       \
    auto real = reinterpret_cast<name##_fptr>(gotcha_get_wrappee(name##_handle));      \
    if (real == nullptr) return _dc_r;                                                 \
    datacrumbs::client::gotcha_wrap::Guard _dc_g;                                      \
    if (!_dc_g.entered) return real vargs;                                             \
    const std::uint64_t _dc_t0 = datacrumbs::client::gotcha_wrap::mono_ns();           \
    _dc_r = real vargs;                                                                \
    const std::uint64_t _dc_t1 = datacrumbs::client::gotcha_wrap::mono_ns();           \
    DC_GOTCHA_RECORD(name, cls, argrecs,                                               \
                     datacrumbs::client::gotcha_wrap::capture_ret(                     \
                         _dc_r, _dc_args, _dc_n, sizeof(_dc_args), _dc_nums, _dc_nn);) \
    return _dc_r;                                                                      \
  }

#define DC_GOTCHA_WRAPPER_1(name, cls, ret, params, vargs, argrecs)               \
  static void name##_dcwrap params {                                              \
    auto real = reinterpret_cast<name##_fptr>(gotcha_get_wrappee(name##_handle)); \
    if (real == nullptr) return;                                                  \
    datacrumbs::client::gotcha_wrap::Guard _dc_g;                                 \
    if (!_dc_g.entered) {                                                         \
      real vargs;                                                                 \
      return;                                                                     \
    }                                                                             \
    const std::uint64_t _dc_t0 = datacrumbs::client::gotcha_wrap::mono_ns();      \
    real vargs;                                                                   \
    const std::uint64_t _dc_t1 = datacrumbs::client::gotcha_wrap::mono_ns();      \
    DC_GOTCHA_RECORD(name, cls, argrecs, )                                        \
  }

#define DC_GOTCHA_WRAPPER_PICK(is_void) DC_GOTCHA_WRAPPER_##is_void
#define DC_GOTCHA_WRAPPER(name, cls, ret, params, vargs, argrecs, is_void) \
  DC_GOTCHA_WRAPPER_PICK(is_void)(name, cls, ret, params, vargs, argrecs)

#define DC_GOTCHA_BINDING(name, cls, ret, params, vargs, argrecs, is_void) \
  {#name, reinterpret_cast<void*>(name##_dcwrap), &name##_handle},

// The class of each binding, in the same order, so a selection can name a role rather than listing
// every symbol that plays it.
#define DC_GOTCHA_CLASS(name, cls, ret, params, vargs, argrecs, is_void) #cls,

#endif  // DATACRUMBS_UTILS_CLIENT_GOTCHA_WRAP_H
